# Generated by Django 4.2.9 on 2024-02-08 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_group_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdegrees',
            name='subjects',
            field=models.ManyToManyField(related_name='subject_groups', to='core.subject'),
        ),
        migrations.AlterField(
            model_name='createclass',
            name='class_degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classdegrees'),
        ),
        migrations.AlterField(
            model_name='createclass',
            name='primary_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_teacher', to='core.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.parent'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.createclass'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_teacher', to='core.teacher'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
